chamberSize: 6            # Total number of chambers in the revolver
bulletCount: 1            # Number of bullets loaded
maxPlayers: 4             # Maximum players per lobby
roundDelayTicks: 60       # Delay between turns (60 ticks = ~3 seconds)
startGameMessage: "&aStarting Russian Roulette!"
spinningDrumMessage: "&e%player% spins the chamber..."
safeMessage: "&aClick... You survived!"
shotMessage: "&cBANG! You lost..."